### ISSUE TITLE
<DEV> Captura Comum

### ISSUE THREAD

**Issue by rpamaral** [igordcsouza/damas#47]

**Comment by Lucianodsn** [comment]
A Captura comum já está com progresso de 60 %

**Comment by igordcsouza** [comment]
Onde esta? Precisamos terminar isso até amanha na hora da reunião, e ainda tenho coisas pra fazer depois disso.
Onde esta o que voce fez até agora? Coloca no repositório para eu tentar terminar isso.
@Lucianodsn

**Comment by igordcsouza** [comment]
Feito, esta no branch de DEV.
Quem puder teste as coisas por favor.
